liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        my_thumb :
            quality : 95
            filters :
                thumbnail  : { size : [300, null ], mode : outbound }