<?php

namespace AdminBundle\Repository;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Query;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Routing\Router;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * Create a QueryBuilder to get all application in 1 request not in 1400+
     *
     * @param bool $userId
     * @return array
     */
    public function getApplications($userId = false, ContainerInterface $container)
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a')
            ->leftJoin('a.user', 'u');
        $query->addSelect('u');

        if ($userId) {
            $query->where('u.id = :userId');
            $query->setParameter('userId', $userId);
        }

        $query->orderBy('a.id', Criteria::DESC);

        $list = $query->getQuery()->getResult(Query::HYDRATE_ARRAY);
        $result = [];
        $urlGenerate = $container->get('router');
        $authorizationChecker = $container->get('security.authorization_checker');

        foreach ($list as $item) {

            $var['appId'] = $item['id'];
            $var['name'] = $item['name'];
            $var['date'] = (is_a($item['date'], 'DateTime')) ? $item['date']->format('d/m/Y  h:m') : $item['date'];
            $var['status'] = $item['status'];
            $var['locked'] = $item['locked'];
            $var['statusChangeDate'] = (is_a($item['statusChangeDate'], 'DateTime'))
                ? $item['statusChangeDate']->format('d/m/Y  h:m') : '';
            $var['userName'] = (!isset($item['user']['username'])) ? '' : $item['user']['username'];

            $var['admin_app_print'] = $urlGenerate->generate(
                'admin_app_print',
                ['id' => $item['id']],
                Router::ABSOLUTE_PATH
            );
            $var['admin_app_edit'] = $urlGenerate->generate(
                'admin_app_edit',
                ['id' => $item['id']],
                Router::ABSOLUTE_PATH
            );
            $var['admin_app_del'] = $urlGenerate->generate(
                'admin_app_del',
                ['id' => $item['id']],
                Router::ABSOLUTE_PATH
            );

            // $var['admin_app_approve'] = ($authorizationChecker->isGranted(
            //     'ROLE_SUPERADMIN'
            // )) ? $urlGenerate->generate(
            //     'admin_app_approve',
            //     ['id' => $item['id']],
            //     Router::ABSOLUTE_PATH
            // ) : false;
            $var['admin_app_approve'] =  $urlGenerate->generate(
                'admin_app_approve',
                ['id' => $item['id']],
                Router::ABSOLUTE_PATH
            );

            // $var['admin_app_reject'] = ($container->get('security.authorization_checker')->isGranted(
            //     'ROLE_SUPERADMIN'
            // )) ? $urlGenerate->generate(
            //     'admin_app_reject',
            //     ['id' => $item['id']],
            //     Router::ABSOLUTE_PATH
            // ) : false;
            $var['admin_app_reject'] =  $urlGenerate->generate(
                'admin_app_reject',
                ['id' => $item['id']],
                Router::ABSOLUTE_PATH
            );

            $result[] = $var;
        }

        return $result;
    }






    /**
     * Create a QueryBuilder to get all application in 1 request not in 1400+
     *
     * @return array
     */
    public function getAllApplicationsLow(ContainerInterface $container)
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a')
            ->leftJoin('a.user', 'u');
        $query->addSelect('u');


        $query->orderBy('a.id', Criteria::DESC);

        $list = $query->getQuery()->getResult(Query::HYDRATE_ARRAY);
        $result = [];
        $urlGenerate = $container->get('router');
        $authorizationChecker = $container->get('security.authorization_checker');

        foreach ($list as $item) {

            $var['appId'] = $item['id'];
            $var['name'] = $item['name'];
            $var['date'] = (is_a($item['date'], 'DateTime')) ? $item['date']->format('d/m/Y  h:m') : $item['date'];
            $var['status'] = $item['status'];
            $var['locked'] = $item['locked'];
            $var['illness'] = $item['illness'];
            $var['purpose'] = $item['purpose'];
            $var['amount'] = $item['amount'];
            $var['statusChangeDate'] = (is_a($item['statusChangeDate'], 'DateTime'))
                ? $item['statusChangeDate']->format('d/m/Y  h:m') : '';
            $var['userName'] = (!isset($item['user']['username'])) ? '' : $item['user']['username'];

            $result[] = $var;
        }

        return $result;
    }


}
