<?php

namespace AdminBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends \Doctrine\ORM\EntityRepository
{


  public function getNewApplicationEmail(){}
}
