services:
#    margaret.example:
#        class: MargaretBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


    app.form.profile:
        class: MargaretBundle\Form\UserType
        tags:
            - { name: form.type, alias: app_user_profile }

    appliction.event_listener:
        class: AdminBundle\EventListener\ApplicationEventListener
        arguments: ["@mailer","%admin_email%","@doctrine.orm.default_entity_manager","@session.flash_bag","@twig","%mailer_noreply%","@form.factory"]
        tags:
            - { name: kernel.event_listener, event: new.application, method: sendEmailToUserOnNewApp  }
            - { name: kernel.event_listener, event: new.application, method: sendEmailToAdminOnNewApp  }
